name: Generate Snake Animation

on:
  schedule:
    # Runs at minute 0 of every 12th hour (e.g., 00:00, 12:00 UTC)
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure full history is fetched

      # Step 2: Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: smriti2911
          svg_out_path: output/github-contribution-grid-snake.svg

      # Step 3: Commit and Push Changes
      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update Snake animation [skip ci]" || echo "No changes to commit"

      # Step 4: Deploy to GitHub Pages
      - name: Deploy Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
